### ISSUE TITLE
Surrounding Tree Analysis

### ISSUE THREAD

**Issue by nhegwood** [eoway/tall-trees-research#10]
In dan_dat.r, if you search for "Elsa Help" or "surrounding tree analysis dataset" (line 164), you will find my workflow and the corresponding code to what I have figured out so far. Thank you!!

**Comment by eoway** [comment]
Thanks! I'll take a look at this tonight/tomorrow and will commit a new version of the code asap.

**Comment by eoway** [comment]
I updated the code and added comments labeled with #EO. I left 6 and 7 for you to finalize, but let me know if you run into additional road blocks or questions.
