### ISSUE TITLE
Converting values over 100 to NA

### ISSUE THREAD

**Issue by nhegwood** [eoway/tall-trees-research#11]
In heightdat.r (located in PRISE folder), line 15 (heightdat[heightdat > 100] <- NA) does not seem to work despite my many attempts. I also tried to use the NAvalue() function to set values over 100 in the raster to NA, and that seemed to do something, but it definitely didn't convert all of them for some reason? For context, this is for the raster height map that I sent you a screenshot of last week. I just wanted to see if you had any ideas for why this isn't working?

Thanks! 
Naomi

**Comment by eoway** [comment]
Strange! Can you add the Forest_height_2019_SASIA.tif to the shared Google Drive folder so that I can take a look?

Link here: https://drive.google.com/drive/u/0/folders/1zPhSD_apM2S1LUCUgJ1qfTB9m3j8jt3t

**Comment by nhegwood** [comment]
I have tried is.na and na.omit and NAvalue, along with heightdat[heightdat > 100] <- NA with no luck - is there anything else I should try?

**Comment by eoway** [comment]
I think the file was just too large to do the NA conversion on a computer without running into memory issues in R. I used ENVI to convert all values >100 to 0 and subset the data to the SE Asian countries of interest (using the shapefile I sent you). I added the updated file to Google Drive (Forest_height_2019_SASIA_subset.tif).
