### ISSUE TITLE
Soils data

### ISSUE THREAD

**Issue by nhegwood** [eoway/tall-trees-research#12]
Hi! I hope everything is going well! I was just wondering if you could try running the soils code on your computer to see if it works on yours? I tried on the desktop and on my laptop and received different errors on both? The errors arise when trying to run gdalinfo (line 72) and gdal_translate (line 90 in heightdat.r (located in the PRISE folder)). The code is just copy and pasted from the website tutorial we found.

Thanks!

**Comment by eoway** [comment]
See my email about soils data. I'm downloading from Google Earth Engine instead because I think it will take too long to debug this issue in R.
